### ISSUE TITLE
Posibilidad de multiples LU identicas

### ISSUE THREAD

**Issue by DarioRv** [21Enzo17/asist.io#18]
## Estado actual

El LU de un estudiante se maneja como un valor `unique` . Este modelo no permite la alta de un estudiante que tenga el mismo LU pero que pertenezca a una Universidad distinta.

## Posibles soluciones

Remover que el LU de un estudiante sea un valor `unique` y dejar el `id` como identificador único

> [!CAUTION]
> Implementar esta solución implicaría que el método `obtenerEstudiantePorLu` quede obsoleto.

---

Configurar el campo `id` y `lu` como una clave primaria compuesta.

> [!CAUTION]
> Implementar esta solución implicaría mayor complejidad a la hora de realizar consultas en la entidad `Estudiante`.

**Comment by 21Enzo17** [comment]
Se cambia la relación de curso a estudiantes de uno a muchos, de esta manera `LU` se puede repetir siempre y cuando no sea en el mismo curso.

**Comment by DarioRv** [comment]
> Se cambia la relación de curso a estudiantes de uno a muchos, de esta manera `LU` se puede repetir siempre y cuando no sea en el mismo curso.

Es incorrecto. El campo `LU` no se puede repetir de ningún modo al ser marcada como `unique`.

## Ejemplo

En la tabla `alumnos` vemos que la estudiante "Fuentes Valeria" con LU "APU00028" esta inscripta en el curso con id "34ecf477-dec7-4ee3-ab11-05db5f521e32".

![image](https://github.com/21Enzo17/asist.io/assets/96150592/a9db2236-706d-4620-a584-056958ff61ff)


Al momento de guardar un alumno con el mismo LU, que posee Valeria, en un curso diferente da como resultado un error de entrada duplicada.

![image](https://github.com/21Enzo17/asist.io/assets/96150592/3dd87fcd-1971-4792-af67-383114e64ae3)
